import { asArray, asNumber, asOptionalString, asString, isRecord, postJson, requestJson } from "../workbench/api";
const ROOT = "/api/functional-operations";
export interface OperationSession { sessionCode: string; title: string; platform: string; externalSessionId?: string; accountId?: string; targetResourceId?: string; sourceTimezone: string; sourceEvidence: Record<string, unknown>; projectCode?: string; liveRoomPlanCode?: string; variantCode?: string; releaseCode?: string; startedAt: string; endedAt: string; metrics: Record<string, number>; sourceKind: string; }
export interface ContentExposure { exposureCode: string; sessionCode: string; planCode: string; variantCode: string; releaseCode?: string; sceneCode: string; startedAt: string; endedAt: string; sourceKind: string; evidenceNote: string; confidence: number; status: string; }
export interface AttributionGroup { scopeType: string; scopeCode: string; displayLabel: string; average: number; sampleSize: number; sessionCodes: string[]; sourceEvidence: { exposureCount: number; releaseBoundExposureCount: number; coverageSeconds: number; sourceKindCounts: Record<string, number>; sceneCodes: string[]; releaseCodes: string[]; averageConfidence?: number; }; limitations: string[]; }
export interface AttributionReport { reportCode: string; metricKey: string; evidenceLevel: string; sessionCodes: string[]; groups: AttributionGroup[]; metadata: { method: string; metricGrain: string; selectedSessionCount: number; observedSessionCount: number; sessionOnlyCount: number; sourceKindCounts: Record<string, number>; releaseBoundExposureCount: number; }; createdAt: string; }
export interface SchedulePlan { scheduleCode: string; title: string; roomId: string; startsAt: string; durationMinutes: number; status: string; conflictCodes: string[]; }
const strings = (value: unknown) => asArray(value).flatMap((item) => typeof item === "string" ? [item] : []);
function session(value: unknown): OperationSession { if (!isRecord(value)) throw new Error("运营场次响应无效"); return { sessionCode: asString(value.session_code), title: asString(value.title), platform: asString(value.platform), externalSessionId: asOptionalString(value.external_session_id), accountId: asOptionalString(value.account_id), targetResourceId: asOptionalString(value.target_resource_id), sourceTimezone: asString(value.source_timezone, "UTC"), sourceEvidence: isRecord(value.source_evidence) ? value.source_evidence : {}, projectCode: asOptionalString(value.content_project_code), liveRoomPlanCode: asOptionalString(value.live_room_plan_code), variantCode: asOptionalString(value.variant_code), releaseCode: asOptionalString(value.release_code), startedAt: asString(value.started_at), endedAt: asString(value.ended_at), metrics: isRecord(value.metrics) ? Object.fromEntries(Object.entries(value.metrics).map(([key, item]) => [key, typeof item === "number" ? item : 0])) : {}, sourceKind: asString(value.source_kind) }; }
function exposure(value: unknown): ContentExposure { if (!isRecord(value)) throw new Error("内容曝光响应无效"); return { exposureCode: asString(value.exposure_code), sessionCode: asString(value.session_code), planCode: asString(value.plan_code), variantCode: asString(value.variant_code), releaseCode: asOptionalString(value.release_code), sceneCode: asString(value.scene_code), startedAt: asString(value.started_at), endedAt: asString(value.ended_at), sourceKind: asString(value.source_kind), evidenceNote: asString(value.evidence_note), confidence: asNumber(value.confidence), status: asString(value.status) }; }
function counts(value: unknown): Record<string, number> { return isRecord(value) ? Object.fromEntries(Object.entries(value).flatMap(([key, item]) => typeof item === "number" ? [[key, item]] : [])) : {}; }
function report(value: unknown): AttributionReport { if (!isRecord(value)) throw new Error("归因响应无效"); const raw = isRecord(value.results) ? value.results : {}; const groupsRaw = isRecord(raw.groups) ? raw.groups : raw; const metadata = isRecord(raw.metadata) ? raw.metadata : {}; return { reportCode: asString(value.report_code), metricKey: asString(value.metric_key), evidenceLevel: asString(value.evidence_level), sessionCodes: strings(value.session_codes), groups: Object.entries(groupsRaw).flatMap(([key, item]) => { if (!isRecord(item)) return []; const evidence = isRecord(item.source_evidence) ? item.source_evidence : {}; return [{ scopeType: asString(item.scope_type, "legacy"), scopeCode: asString(item.scope_code, key), displayLabel: asString(item.display_label, key), average: asNumber(item.average), sampleSize: asNumber(item.sample_size), sessionCodes: strings(item.session_codes), sourceEvidence: { exposureCount: asNumber(evidence.exposure_count), releaseBoundExposureCount: asNumber(evidence.release_bound_exposure_count), coverageSeconds: asNumber(evidence.coverage_seconds), sourceKindCounts: counts(evidence.source_kind_counts), sceneCodes: strings(evidence.scene_codes), releaseCodes: strings(evidence.release_codes), averageConfidence: typeof evidence.average_confidence === "number" ? evidence.average_confidence : undefined }, limitations: strings(item.limitations) }]; }), metadata: { method: asString(metadata.method, "legacy_session_summary"), metricGrain: asString(metadata.metric_grain, "operation_session"), selectedSessionCount: asNumber(metadata.selected_session_count, strings(value.session_codes).length), observedSessionCount: asNumber(metadata.observed_session_count), sessionOnlyCount: asNumber(metadata.session_only_count), sourceKindCounts: counts(metadata.source_kind_counts), releaseBoundExposureCount: asNumber(metadata.release_bound_exposure_count) }, createdAt: asString(value.created_at) }; }
function schedule(value: unknown): SchedulePlan { if (!isRecord(value)) throw new Error("排播响应无效"); return { scheduleCode: asString(value.schedule_code), title: asString(value.title), roomId: asString(value.target_live_room_id), startsAt: asString(value.starts_at), durationMinutes: asNumber(value.duration_minutes), status: asString(value.status), conflictCodes: strings(value.conflict_codes) }; }
export const operationsApi = { listSessions: () => requestJson<unknown[]>(`${ROOT}/sessions`).then((rows) => rows.map(session)), createSession: (payload: Record<string, unknown>) => postJson<unknown>(`${ROOT}/sessions`, payload).then(session), listExposures: () => requestJson<unknown[]>(`${ROOT}/exposures`).then((rows) => rows.map(exposure)), createExposure: (payload: Record<string, unknown>) => postJson<unknown>(`${ROOT}/exposures`, payload).then(exposure), listReports: () => requestJson<unknown[]>(`${ROOT}/attribution-reports`).then((rows) => rows.map(report)), createReport: (payload: Record<string, unknown>) => postJson<unknown>(`${ROOT}/attribution-reports`, payload).then(report), listSchedules: () => requestJson<unknown[]>(`${ROOT}/schedule-plans`).then((rows) => rows.map(schedule)), createSchedule: (payload: Record<string, unknown>) => postJson<unknown>(`${ROOT}/schedule-plans`, payload).then(schedule) };
